name: Unit Test
run-name: ${{ github.actor }} is testing 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@main
      - run: ls 
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python -m unittest tests/test_models.py
      - run: python -m unittest tests/test_routes.py
      
